# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  ceci est mon espace a moi.. que j'aime bien ^^.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: JulietteDefranc
github_username:  jekyll

# Build settings
markdown: kramdown
