# Site settings
title: Juliette se raconte
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ici vous allez pouvoir découvrir le monde magique du multimédia, qui plus est en ma compagnie (héhé)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: JulietteDefranc
github_username:  JulietteDefrance

# Build settings
markdown: kramdown
